package com.mucommander;

import com.mucommander.text.Activator;
import com.mucommander.text.Translator;
import com.mucommander.ui.chooser.PreviewLabel;
import org.junit.BeforeClass;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collections;
import java.util.Locale;
import java.util.Random;

public class LogGeneration {
    private static final Logger LOGGER = LoggerFactory.getLogger(Logger.class);
    Random random = new Random();

    @Test
    public void testSetTextPainted() throws InterruptedException {
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S4");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S4->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S4");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S4->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S4");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S4->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S4");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S4->S5");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S5->S1");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S1->S2");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S2->S3");
        Thread.sleep(random.nextInt(15000));
        LOGGER.info("S3->S5");
        Thread.sleep(random.nextInt(15000));

    }
}
